version: "2"

services:
  api:
    image: "bionexo:latest"
    build: .
    ports:
      - 8088:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:~/test
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure
